fixed default startup-cfg.xml save path
git-svn-id: https://yuma.svn.sourceforge.net/svnroot/yuma/trunk@720 1ffd1d58-2efc-45df-af60-190a33ec9863

diff --git a/libtoaster/src/Makefile b/libtoaster/src/Makefile
--- a/libtoaster/src/Makefile
+++ b/libtoaster/src/Makefile
@@ -1,4 +1,5 @@
-# Makefile for Yuma Server Instrumentation Library
+
+# SIL Makefile for Yuma Server Instrumentation Library
 #  
 
 ############### SOURCE PROFILE ##############################
@@ -13,31 +14,215 @@ TARGET=../bin
 
 LIB_INST=../lib
 
-WORK_INST=../../netconf/target/lib
+WORK_INST=$(YUMA_HOME)/target/lib
 
 REAL_INST=$(DESTDIR)/usr/lib/yuma
-
 
 #################### MAKE RULES ########################
 
 all: sil_dummy sil_lib
 
 #################### PLATFORM DEFINITIONS ############
-include ../../netconf/src/platform/platform.profile.sil
 
-include ../../netconf/src/platform/platform.profile.cmn
+ifdef RELEASE
+CINC = -I. \
+     -I../../netconf/src/platform \
+     -I../../netconf/src/ncx \
+     -I../../netconf/src/agt
+else
+ifdef YUMA_HOME
+CINC = -I. \
+     -I$(YUMA_HOME)/src/platform \
+     -I$(YUMA_HOME)/src/ncx \
+     -I$(YUMA_HOME)/src/agt
+else
+ifdef YUMA_INSTALL
+CINC = -I. \
+     -I$(YUMA_INSTALL)/src/platform \
+     -I$(YUMA_INSTALL)/src/ncx \
+     -I$(YUMA_INSTALL)/src/agt
+else
+CINC = -I. \
+     -I/usr/share/yuma/src/netconf/src/platform \
+     -I/usr/share/yuma/src/netconf/src/ncx \
+     -I/usr/share/yuma/src/netconf/src/agt
+endif
+endif
+endif
+
+CINC += -I/usr/include -I/usr/include/libxml2 -I/usr/include/libxml2/libxml
+
+# added /sw/include for MacOSX
+ifdef MAC
+# MACOSX version
+  CINC +=-I/sw/include
+  CFLAGS += -DMACOSX=1
+endif
+
+LBASE=../lib
+
+ifdef DESTDIR
+OWNER=
+else
+ifdef MAC
+OWNER=-oroot
+else
+OWNER= --owner=root
+endif
+endif
+
+### GCC + [LINUX or MACOSX]
+
+CWARN=-Wall -Wno-long-long -Wformat-y2k -Winit-self \
+	-Wmissing-include-dirs -Wswitch-default -Wunused-parameter \
+	-Wextra -Wundef -Wshadow -Wpointer-arith \
+	-Wwrite-strings -Wbad-function-cast -Wcast-qual -Wcast-align \
+	-Waggregate-return -Wstrict-prototypes -Wold-style-definition \
+	-Wmissing-prototypes -Wmissing-declarations \
+	-Wpacked -Winvalid-pch \
+	-Wredundant-decls -Wnested-externs -Winline -std=gnu99 -Werror
+
+
+# -Wunreachable-code removed due to -O3
+# -O3 changed to -O2 due to code bloat from inline functions
+
+CDEFS=-DDEBUG -DLINUX -DGCC
+
+ifndef NOFLOAT
+  CDEFS += -DHAS_FLOAT
+endif
+
+CFLAGS=$(CDEFS) $(CWARN) -fPIC
+
+# production (0) or debug (1) build
+ifdef DEBUG
+  CFLAGS += -ggdb3
+else
+  CFLAGS += -O2
+endif
+
+# memory leak debugging mode
+ifdef MEMTRACE
+  CFLAGS += -DMEMORY_DEBUG=1
+endif
+
+# free or SDK version
+ifdef FREE
+  CFLAGS += -DFREE_VERSION
+endif
+
+ifdef RELEASE
+  CFLAGS += -DRELEASE=$(RELEASE)
+endif
+
+ifdef MAC
+   GRP=
+else
+ifdef DESTDIR
+   GRP=
+else
+   GRP=--group=root
+endif
+endif
+
+ifdef STATIC
+LIBSUFFIX=a
+else
+ifdef MAC
+LIBSUFFIX=dylib
+else
+LIBSUFFIX=so
+endif
+endif
+
+CC=gcc
+LINK=gcc
+LINT=splint
+LINTFLAGS= '-weak -macrovarprefix "m_"'
+##LIBFLAGS=-lsocket
+
+LIBTOOL=ar
+#LFLAGS=-v --no-as-needed
+LFLAGS=-lm
+LPATH=-L$(LBASE)
+
+CEES = $(wildcard *.c)
+
+HEES = $(wildcard *.h)
+
+################ OBJS RULE #############
+OBJS = $(patsubst %.c,$(TARGET)/%.o,$(CEES))
+
+################ DEPS RULE #############
+DEPS = $(patsubst %.c,%.D,$(wildcard *.c))
+
+######################## PLATFORM DEFINITIONS #############
+PLATFORM_CPP=
+
+.PHONY: all superclean clean test install uninstall \
+        distclean depend lint
+
+######################### MAKE DEPENDENCIES ###############
+COMPILE.c= $(CC) $(CFLAGS) $(CPPFLAGS) $(PLATFORM_CPP) \
+           $(CINC) $(SUBDIR_CPP) $(TARGET_ARCH) -c
+
+
+$(TARGET)/%.o: %.c
+	$(CC) $(CFLAGS) $(CPPFLAGS) $(PLATFORM_CPP) \
+        $(CINC) $(SUBDIR_CPP) $(TARGET_ARCH) -c -o $@ $< 
+
+
+# Common library rule
+
+$(LBASE)/lib%.a: $(OBJS)
+	$(LIBTOOL) cr $@ $(OBJS)
+	ranlib $@
+
+# dependency rule to make temp .D files from .c sources
+# all the .D files are collected and appended to the
+# appropriate Makefile when 'make depend' is run
+# this rule is kept here to make sure it matches COMPILE.c
+%.D: %.c
+	$(CC) -MM -MG -MT $(TARGET)/$(patsubst %.c,%.o,$<) \
+	-Wall -Wcomment $(CPPFLAGS) $(PLATFORM_CPP) $(CINC) \
+	$(SUBDIR_CPP) $(TARGET_ARCH) -c $< > $@
+
+
+################## MAKE DEPENDENCIES #####################
+# following depend rule is the GNU version! Other versions TBD
+# this rule cannot be included by the top level makefile
+# so platform.profile.cmn was created to allow that Makefile
+# to define a different 'depend' rule.
+depend: dependencies
+
+dependencies: $(DEPS)
+	@if [ ! -f Makefile ]; then \
+	    echo "Error: Makefile missing!"; \
+	    exit 1; \
+	fi
+	@rm -f dependencies
+	@for i in $(DEPS); do \
+	  if [ -f $$i ] ; then \
+	    (cat $$i >> dependencies; echo "" >> dependencies) ; \
+	  else \
+	    (echo "*** Warning: Dependency file $i.D is missing! (Skipping...) ***"; \
+	     echo "# Warning: Missing file $$i !!!") ; \
+	  fi; \
+	done
+	@echo "" >> dependencies
+# delete the .D files to force make depend to rebuild them each time
+# that target is built
+#	@rm -f $(DEPS)
+
 
 ################ DEPENDENCIES #########################
 # depend rule must be included after the 'all' make rule
-
-include ../../netconf/src/platform/platform.profile.depend
-
 
 test:
 
 install:
 	mkdir -p $(REAL_INST)
-	$(SUDO) install $(LIB_INST)/lib$(SUBDIR_NM).$(LIBSUFFIX) $(REAL_INST)
+	install $(LIB_INST)/lib$(SUBDIR_NM).$(LIBSUFFIX) $(REAL_INST)
 
 work:
 	install $(LIB_INST)/lib$(SUBDIR_NM).$(LIBSUFFIX) $(WORK_INST)
